const E=0,B=1,W=2,D=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];
const rivals=[['ソフトクリーム','🍦',0,'とける前に、ひと勝負。'],['木馬のポニー','🎠',1,'ゆっくり考えよう。'],['すべり台','🛝',2,'角まで一直線だよ。'],['赤いブランコ','🎡',3,'ゆらゆら読んでるよ。'],['公園のハト','🕊️',4,'そこ、いただき。'],['砂場の王さま','🏰',5,'守りは固いよ。'],['噴水くん','⛲',6,'流れが見えてきた。'],['どんぐり親分','🌰',7,'角は渡さないぞ。'],['ベンチ先生','🪑',8,'少し先まで見よう。'],['時計塔','🕰️',9,'最後まで読めるかな。']];
let board,turn=B,active=0,locked=false,history=[],hintCell='';
const q=s=>document.querySelector(s), boardEl=q('#board'),hand=q('#hand');
function reset(){board=Array.from({length:8},()=>Array(8).fill(E));board[3][3]=board[4][4]=W;board[3][4]=board[4][3]=B;turn=B;locked=false;history=[];hintCell='';q('#result').className='';q('.scene').classList.remove('victory');say(rivals[active][3]);render()}
function flips(src,r,c,color){if(src[r][c])return[];let out=[];for(const[dr,dc]of D){let line=[],y=r+dr,x=c+dc;while(y>=0&&y<8&&x>=0&&x<8&&src[y][x]===3-color){line.push([y,x]);y+=dr;x+=dc}if(line.length&&y>=0&&y<8&&x>=0&&x<8&&src[y][x]===color)out.push(...line)}return out}
function moves(src,color){let a=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){let f=flips(src,r,c,color);if(f.length)a.push({r,c,f})}return a}
function render(anim=[]){boardEl.innerHTML='';q('#rivalFace').textContent=rivals[active][1];q('#seatedRival').classList.toggle('thinking',locked);let legal=turn===B&&!locked?moves(board,B):[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){let b=document.createElement('button');b.className='cell';b.dataset.r=r;b.dataset.c=c;let lm=legal.find(m=>m.r===r&&m.c===c);if(lm){b.classList.add('legal');b.dataset.flips=lm.f.length;if((r===1||r===6)&&(c===1||c===6))b.classList.add('danger')}if(hintCell===`${r}-${c}`)b.classList.add('best-hint');if(board[r][c]){let d=document.createElement('i');d.className=`disc ${board[r][c]===B?'black':'white'}`;if(anim.some(p=>p[0]===r&&p[1]===c))d.classList.add('flip');b.append(d)}boardEl.append(b)}let n=count();q('#black').textContent=n.b;q('#white').textContent=n.w;q('#turn').textContent=locked?'考え中…':turn===B?'あなたの番':rivals[active][0]+'の番'}
function count(){return board.flat().reduce((n,v)=>(v===B?n.b++:v===W?n.w++:0,n),{b:0,w:0})}
function place(m,color){history.push(board.map(r=>[...r]));board[m.r][m.c]=color;m.f.forEach(([r,c])=>board[r][c]=color);animateHand(m,()=>{render(m.f);let cell=boardEl.children[m.r*8+m.c],disc=cell?.querySelector('.disc');disc?.classList.add('drop');try{webkit.messageHandlers.haptic.postMessage('place')}catch(e){}setTimeout(()=>next(color),380)})}
function animateHand(m,done){let cell=boardEl.children[m.r*8+m.c],a=cell.getBoundingClientRect(),p=q('.scene').getBoundingClientRect();hand.style.setProperty('--x',`${a.left-p.left+a.width/2}px`);hand.style.setProperty('--y',`${a.top-p.top+a.height/2-18}px`);hand.classList.remove('place');void hand.offsetWidth;hand.classList.add('place');setTimeout(done,620)}
function next(color){turn=3-color;if(!moves(board,turn).length){turn=color;if(!moves(board,turn).length)return finish()}if(turn===W){locked=true;render();say('うーん、ここかな…');setTimeout(ai,650)}else{locked=false;render();say('次はどこに置く？')}}
const POS=[[120,-35,20,8,8,20,-35,120],[-35,-55,-8,-6,-6,-8,-55,-35],[20,-8,15,4,4,15,-8,20],[8,-6,4,2,2,4,-6,8],[8,-6,4,2,2,4,-6,8],[20,-8,15,4,4,15,-8,20],[-35,-55,-8,-6,-6,-8,-55,-35],[120,-35,20,8,8,20,-35,120]];
function simulate(src,m,color){let n=src.map(row=>[...row]);n[m.r][m.c]=color;m.f.forEach(([r,c])=>n[r][c]=color);return n}
function value(src){let v=0,b=0,w=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++){if(src[r][c]===W){v+=POS[r][c];w++}if(src[r][c]===B){v-=POS[r][c];b++}}return v+(moves(src,W).length-moves(src,B).length)*9+(w-b)*2}
function minimax(src,color,depth,a=-1e9,z=1e9){let ms=moves(src,color);if(!depth||(!ms.length&&!moves(src,3-color).length))return value(src);if(!ms.length)return minimax(src,3-color,depth-1,a,z);if(color===W){let best=-1e9;for(const m of ms){best=Math.max(best,minimax(simulate(src,m,color),B,depth-1,a,z));a=Math.max(a,best);if(z<=a)break}return best}let best=1e9;for(const m of ms){best=Math.min(best,minimax(simulate(src,m,color),W,depth-1,a,z));z=Math.min(z,best);if(z<=a)break}return best}
function ai(){let ms=moves(board,W);if(!ms.length)return next(W);let level=rivals[active][2],depth=level<4?0:level<7?1:level<9?2:3;let ranked=ms.map(m=>({m,score:depth?minimax(simulate(board,m,W),B,depth):value(simulate(board,m,W))})).sort((a,b)=>b.score-a.score);let pool=level===0?ranked:ranked.slice(0,Math.max(1,5-Math.floor(level/2)));let pick=level>=8?pool[0]:pool[Math.floor(Math.random()*pool.length)];place(pick.m,W)}
function finish(){locked=true;let n=count(),win=n.b>n.w;q('#resultTitle').textContent=n.b===n.w?'引き分け':win?'あなたの勝ち！':rivals[active][0]+'の勝ち';q('#resultScore').textContent=`あなた ${n.b} — ${n.w} ${rivals[active][0]}`;if(win){q('.scene').classList.add('victory');say('噴水までお祝いしてる！')}setTimeout(()=>q('#result').className='show',win?2400:450)}
function say(t){q('#rivalName').textContent=rivals[active][1]+' '+rivals[active][0];q('#line').textContent=t}
function makeRivals(){rivals.forEach((r,i)=>{let b=document.createElement('button');b.className='rival'+(i===0?' active':'');b.textContent=r[1];b.title=r[0];b.onclick=()=>{active=i;document.querySelectorAll('.rival').forEach((x,j)=>x.classList.toggle('active',j===i));reset()};q('#rivalList').append(b)})}
boardEl.onclick=e=>{let c=e.target.closest('.cell');if(!c||locked||turn!==B)return;let m=moves(board,B).find(x=>x.r==c.dataset.r&&x.c==c.dataset.c);if(m){hintCell='';place(m,B)}};q('#reset').onclick=q('#again').onclick=reset;q('#undo').onclick=()=>{if(!history.length||locked)return;board=history[Math.max(0,history.length-2)].map(r=>[...r]);history=history.slice(0,-2);turn=B;hintCell='';render();say('ひとつ戻したよ。')};q('#hint').onclick=()=>{if(locked||turn!==B)return;let ms=moves(board,B),w=[[100,-30,12,8,8,12,-30,100],[-30,-45,-6,-5,-5,-6,-45,-30],[12,-6,8,3,3,8,-6,12],[8,-5,3,1,1,3,-5,8],[8,-5,3,1,1,3,-5,8],[12,-6,8,3,3,8,-6,12],[-30,-45,-6,-5,-5,-6,-45,-30],[100,-30,12,8,8,12,-30,100]];ms.sort((a,b)=>w[b.r][b.c]+b.f.length*2-w[a.r][a.c]-a.f.length*2);let m=ms[0];if(!m)return;hintCell=`${m.r}-${m.c}`;let corner=(m.r===0||m.r===7)&&(m.c===0||m.c===7);say(corner?'角が取れるよ。ここは最後まで返されない！':m.f.length>=3?`${m.f.length}枚返せるよ。まずはここを試してみよう。`:'ここなら相手に角を渡しにくいよ。');render()};makeRivals();reset();
